# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib_number = [1, 2]
while fib_number[-1] + fib_number[-2] < 4000000
	fib_number << fib_number[-1] + fib_number[-2]
end

sum = 0
fib_number.each {|k| sum+= k if k % 2 == 0}
puts sum


